### ISSUE TITLE
Excluir palabras reservadas (stop words)

### ISSUE THREAD

**Issue by ivansabik** [NOSTRODATA/conferencias_matutinas_amlo#3]
Parece que las imágenes con las tag clouds tienen palabras que no son tan interesantes o relevantes. Seria bueno quitar las palabras reservadas (stop words), por ejemplo aquí hay una lista: https://github.com/Alir3z4/stop-words/blob/master/spanish.txt

**Comment by bustavo** [comment]
Listo! Muchas gracias @ivansabik! Agregando esos cambios.
